#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import sys,os,re,commands

entree="/dev/sdb"
sorties=["/dev/sdc",]
partition=entree

def lit_parts(disque):
	inf={}
	sfdisk_output = commands.getoutput("sfdisk -d %s" % disque)	# on lit la table de partition du disque
	rex=re.compile("%s([0-9]*).*start= *([0-9]*).*size= *([0-9]*).*Id= *([0-9]*),? ?([a-zA-Z]*)?" % disque)
	for line in sfdisk_output.split("\n"):			# on lit ligne par ligne
		if line.startswith("/"):					# si la ligne commence par un / on doit avoir un /dev/sd???
			parts = rex.search(line)
			dev,start,size,identification,bootable=parts.groups()
			if int(size) != 0:
				inf[int(dev)]={'start':int(start), 'size':int(size), 'Id':identification, 'bootable': True if bootable else False}
	return inf

def main():
	parts=lit_parts(entree)
	partitions=sorted(parts.keys())
	for nsortie in sorties:
		com_sfdisk='unit: sectors\n'
		for npart in partitions:
			com_sfdisk += '%s%s : start=%s,size=%s,Id=%s%s\n' % (nsortie,npart,parts[npart]['start'],parts[npart]['size'],parts[npart]['Id'],',bootable' if parts[npart]['bootable']else '')
		print(com_sfdisk)

if __name__ == '__main__':
	main()
