# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dup2.ui'
#
# Created: Fri Oct 24 15:14:58 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(410, 422)
        self.checkBox_2 = QtGui.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 100, 101, 26))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 130, 101, 26))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 160, 101, 26))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 100, 141, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(120, 130, 141, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(120, 160, 141, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.progressBar_2 = QtGui.QProgressBar(Dialog)
        self.progressBar_2.setGeometry(QtCore.QRect(270, 100, 118, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.progressBar_3 = QtGui.QProgressBar(Dialog)
        self.progressBar_3.setGeometry(QtCore.QRect(270, 130, 118, 23))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.progressBar_4 = QtGui.QProgressBar(Dialog)
        self.progressBar_4.setGeometry(QtCore.QRect(270, 160, 118, 23))
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(120, 20, 101, 29))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(120, 70, 141, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.progressBar_5 = QtGui.QProgressBar(Dialog)
        self.progressBar_5.setGeometry(QtCore.QRect(270, 70, 118, 23))
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.checkBox_5 = QtGui.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 70, 101, 26))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 91, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.checkBox_6 = QtGui.QCheckBox(Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 190, 101, 26))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(120, 190, 141, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.progressBar_6 = QtGui.QProgressBar(Dialog)
        self.progressBar_6.setGeometry(QtCore.QRect(270, 190, 118, 23))
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setObjectName(_fromUtf8("progressBar_6"))
        self.checkBox_7 = QtGui.QCheckBox(Dialog)
        self.checkBox_7.setGeometry(QtCore.QRect(20, 220, 101, 26))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(120, 220, 141, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.progressBar_7 = QtGui.QProgressBar(Dialog)
        self.progressBar_7.setGeometry(QtCore.QRect(270, 220, 118, 23))
        self.progressBar_7.setProperty("value", 24)
        self.progressBar_7.setObjectName(_fromUtf8("progressBar_7"))
        self.checkBox_8 = QtGui.QCheckBox(Dialog)
        self.checkBox_8.setGeometry(QtCore.QRect(20, 250, 101, 26))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(120, 250, 141, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.progressBar_8 = QtGui.QProgressBar(Dialog)
        self.progressBar_8.setGeometry(QtCore.QRect(270, 250, 118, 23))
        self.progressBar_8.setProperty("value", 24)
        self.progressBar_8.setObjectName(_fromUtf8("progressBar_8"))
        self.checkBox_9 = QtGui.QCheckBox(Dialog)
        self.checkBox_9.setGeometry(QtCore.QRect(20, 280, 101, 26))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(120, 280, 141, 21))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.progressBar_9 = QtGui.QProgressBar(Dialog)
        self.progressBar_9.setGeometry(QtCore.QRect(270, 280, 118, 23))
        self.progressBar_9.setProperty("value", 24)
        self.progressBar_9.setObjectName(_fromUtf8("progressBar_9"))
        self.checkBox_10 = QtGui.QCheckBox(Dialog)
        self.checkBox_10.setGeometry(QtCore.QRect(20, 310, 101, 26))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(120, 310, 141, 21))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.progressBar_10 = QtGui.QProgressBar(Dialog)
        self.progressBar_10.setGeometry(QtCore.QRect(270, 310, 118, 23))
        self.progressBar_10.setProperty("value", 24)
        self.progressBar_10.setObjectName(_fromUtf8("progressBar_10"))
        self.checkBox_11 = QtGui.QCheckBox(Dialog)
        self.checkBox_11.setGeometry(QtCore.QRect(20, 340, 101, 26))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(120, 340, 141, 21))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.progressBar_11 = QtGui.QProgressBar(Dialog)
        self.progressBar_11.setGeometry(QtCore.QRect(270, 340, 118, 23))
        self.progressBar_11.setProperty("value", 24)
        self.progressBar_11.setObjectName(_fromUtf8("progressBar_11"))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(290, 380, 96, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 380, 96, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(260, 20, 121, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.checkBox_2.setText(_translate("Dialog", "/dev/sdd", None))
        self.checkBox_3.setText(_translate("Dialog", "/dev/sde", None))
        self.checkBox_4.setText(_translate("Dialog", "/dev/sdf", None))
        self.label_2.setText(_translate("Dialog", "partitionnement", None))
        self.label_3.setText(_translate("Dialog", "fmt ext4 /dev/sde3", None))
        self.label_4.setText(_translate("Dialog", "copie /dev/sdf1", None))
        self.label_5.setText(_translate("Dialog", "écriture MBR", None))
        self.checkBox_5.setText(_translate("Dialog", "/dev/sdc", None))
        self.label_6.setText(_translate("Dialog", "Original", None))
        self.checkBox_6.setText(_translate("Dialog", "/dev/sdg", None))
        self.label_7.setText(_translate("Dialog", "mount /dev/sdg3", None))
        self.checkBox_7.setText(_translate("Dialog", "/dev/sdh", None))
        self.label_8.setText(_translate("Dialog", "umount /dev/sdh1", None))
        self.checkBox_8.setText(_translate("Dialog", "/dev/sdi", None))
        self.label_9.setText(_translate("Dialog", "OK !", None))
        self.checkBox_9.setText(_translate("Dialog", "/dev/sdj", None))
        self.checkBox_10.setText(_translate("Dialog", "/dev/sdk", None))
        self.checkBox_11.setText(_translate("Dialog", "/dev/sdl", None))
        self.pushButton.setText(_translate("Dialog", "Quitte", None))
        self.pushButton_2.setText(_translate("Dialog", "Go !", None))
        self.label_14.setText(_translate("Dialog", "nombre de fichiers :", None))

