# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dup.ui'
#
# Created: Fri Oct 17 18:03:17 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(595, 433)
        self.progressBar_11 = QtGui.QProgressBar(Dialog)
        self.progressBar_11.setGeometry(QtCore.QRect(190, 350, 118, 23))
        self.progressBar_11.setProperty("value", 24)
        self.progressBar_11.setObjectName(_fromUtf8("progressBar_11"))
        self.progressBar_2 = QtGui.QProgressBar(Dialog)
        self.progressBar_2.setGeometry(QtCore.QRect(190, 80, 118, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.progressBar_3 = QtGui.QProgressBar(Dialog)
        self.progressBar_3.setGeometry(QtCore.QRect(190, 110, 118, 23))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.progressBar_4 = QtGui.QProgressBar(Dialog)
        self.progressBar_4.setGeometry(QtCore.QRect(190, 140, 118, 23))
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.progressBar_5 = QtGui.QProgressBar(Dialog)
        self.progressBar_5.setGeometry(QtCore.QRect(190, 170, 118, 23))
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.progressBar_6 = QtGui.QProgressBar(Dialog)
        self.progressBar_6.setGeometry(QtCore.QRect(190, 200, 118, 23))
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setObjectName(_fromUtf8("progressBar_6"))
        self.progressBar_7 = QtGui.QProgressBar(Dialog)
        self.progressBar_7.setGeometry(QtCore.QRect(190, 230, 118, 23))
        self.progressBar_7.setProperty("value", 24)
        self.progressBar_7.setObjectName(_fromUtf8("progressBar_7"))
        self.progressBar_8 = QtGui.QProgressBar(Dialog)
        self.progressBar_8.setGeometry(QtCore.QRect(190, 260, 118, 23))
        self.progressBar_8.setProperty("value", 24)
        self.progressBar_8.setObjectName(_fromUtf8("progressBar_8"))
        self.progressBar_9 = QtGui.QProgressBar(Dialog)
        self.progressBar_9.setGeometry(QtCore.QRect(190, 290, 118, 23))
        self.progressBar_9.setProperty("value", 24)
        self.progressBar_9.setObjectName(_fromUtf8("progressBar_9"))
        self.progressBar_10 = QtGui.QProgressBar(Dialog)
        self.progressBar_10.setGeometry(QtCore.QRect(190, 320, 118, 23))
        self.progressBar_10.setProperty("value", 24)
        self.progressBar_10.setObjectName(_fromUtf8("progressBar_10"))
        self.checkBox_2 = QtGui.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(160, 80, 21, 26))
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(160, 110, 21, 26))
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(160, 140, 21, 26))
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(160, 170, 21, 26))
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(160, 200, 21, 26))
        self.checkBox_6.setText(_fromUtf8(""))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_7 = QtGui.QCheckBox(Dialog)
        self.checkBox_7.setGeometry(QtCore.QRect(160, 230, 21, 26))
        self.checkBox_7.setText(_fromUtf8(""))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkBox_8 = QtGui.QCheckBox(Dialog)
        self.checkBox_8.setGeometry(QtCore.QRect(160, 260, 21, 26))
        self.checkBox_8.setText(_fromUtf8(""))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkBox_9 = QtGui.QCheckBox(Dialog)
        self.checkBox_9.setGeometry(QtCore.QRect(160, 290, 21, 26))
        self.checkBox_9.setText(_fromUtf8(""))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkBox_10 = QtGui.QCheckBox(Dialog)
        self.checkBox_10.setGeometry(QtCore.QRect(160, 320, 21, 26))
        self.checkBox_10.setText(_fromUtf8(""))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(130, 20, 121, 29))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 65, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox_2 = QtGui.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 80, 121, 29))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_3 = QtGui.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 110, 121, 29))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_4 = QtGui.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 140, 121, 29))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_5 = QtGui.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 170, 121, 29))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_6 = QtGui.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(20, 200, 121, 29))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_7 = QtGui.QComboBox(Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(20, 230, 121, 29))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_8 = QtGui.QComboBox(Dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(20, 260, 121, 29))
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_9 = QtGui.QComboBox(Dialog)
        self.comboBox_9.setGeometry(QtCore.QRect(20, 290, 121, 29))
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_10 = QtGui.QComboBox(Dialog)
        self.comboBox_10.setGeometry(QtCore.QRect(20, 320, 121, 29))
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_11 = QtGui.QComboBox(Dialog)
        self.comboBox_11.setGeometry(QtCore.QRect(20, 350, 121, 29))
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 91, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pb_go = QtGui.QPushButton(Dialog)
        self.pb_go.setGeometry(QtCore.QRect(370, 390, 96, 31))
        self.pb_go.setObjectName(_fromUtf8("pb_go"))
        self.pb_stop = QtGui.QPushButton(Dialog)
        self.pb_stop.setGeometry(QtCore.QRect(480, 390, 96, 31))
        self.pb_stop.setObjectName(_fromUtf8("pb_stop"))
        self.checkBox_11 = QtGui.QCheckBox(Dialog)
        self.checkBox_11.setGeometry(QtCore.QRect(160, 350, 21, 26))
        self.checkBox_11.setText(_fromUtf8(""))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.lineEdit_2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 80, 251, 33))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 110, 251, 33))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 140, 251, 33))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(320, 170, 251, 33))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(320, 200, 251, 33))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(320, 230, 251, 33))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(Dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(320, 260, 251, 33))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(320, 290, 251, 33))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(Dialog)
        self.lineEdit_10.setGeometry(QtCore.QRect(320, 320, 251, 33))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_11 = QtGui.QLineEdit(Dialog)
        self.lineEdit_11.setGeometry(QtCore.QRect(320, 350, 251, 33))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Original", None))
        self.label_2.setText(_translate("Dialog", "Destinations", None))
        self.pb_go.setText(_translate("Dialog", "Go !", None))
        self.pb_stop.setText(_translate("Dialog", "STOP", None))

